### PR TITLE
v3.0, cleanup and latest API updates.

### PR DESCRIPTION
**Pull request by Ifera**
This PR adds support for PocketMine-MP latest API along with some restyling of entire code. The code is set to meet the standards of Poggit.

### CODE REVIEW

**Comment by Muqsit** [comment]
Can you remove the plugin enable/disable message and type-hint `onEnable()` and `onDisable()` (`: void`)?

**Comment by Ifera** [comment]
Removed the enable/disable messages along with type-hinting `onEnable()`. Not sure if `onDisable()` is required since it was only sending the disable message.

**Comment by Ifera** [comment]
@Muqsit #21 and #20 can be closed now.

**Comment by Ifera** [comment]
@Muqsit sorry to ping you again but you might want to consider releasing this to poggit. Further some people claiming they own sell. [Example](https://github.com/Pocketmine-PHP/Sell). You should report or DMCA that. But its totally up to you.

**Comment by Muqsit** [comment]
Wow, well...

**Pull request merged**
